### ISSUE TITLE
Could you give more information about how to run the code?

### ISSUE THREAD

**Issue by AiHubCN** [PANXiao1994/mRASP2#1]
Thank you for your great job!
Could you give more information about how to run the code?
Such as the data format, script of training and inference.
Thank you very much!

**Comment by Hanlard** [comment]
And is the code complete？

**Comment by PANXiao1994** [comment]
Thank you for your attention! I will update the code, as well as the information in a one week

**Comment by yingwaner** [comment]
We are very interested in your work. Looking forward to your updata of the code!

**Comment by PANXiao1994** [comment]
Hi, thank you for your interest! You can use the `train_w_mono.sh` script to train the model. If you have more questions, please don't hesitate to ask.

**Comment by surviveMiao** [comment]
> We are very interested in your work. Looking forward to your updata of the code!

Hello, have you reproduced the mrasp2 model? If it is convenient for me to ask you some questions?

**Comment by surviveMiao** [comment]
> Thank you for your great job! Could you give more information about how to run the code? Such as the data format, script of training and inference. Thank you very much!

Hello, have you reproduced the mrasp2 model? If it is convenient for me to ask you some questions?

**Comment by Sen-Ran** [comment]
> > Thank you for your great job! Could you give more information about how to run the code? Such as the data format, script of training and inference. Thank you very much!
> 
> Hello, have you reproduced the mrasp2 model? If it is convenient for me to ask you some questions?

请问你成功复现了嘛，我也遇到了一些问题
