### ISSUE TITLE
fairseq-train config question

### ISSUE THREAD

**Issue by wying8349** [PANXiao1994/mRASP2#10]
In the example config, what does min_lr stand for? When I run the command provided in readme, it gives me the following error. 
![7510c29be303e5ef6993c102e56dd95](https://user-images.githubusercontent.com/48537562/133018451-110f5033-9dd5-4a25-858c-fc8fb367e7c3.png)
I checked the fairseq documentation and found this:
![image](https://user-images.githubusercontent.com/48537562/133018871-d2758552-4fe2-414c-8237-0a93ccb94753.png)
Should I use this argument instead? 
Thank you for answering!

**Comment by Maxwell-Lyu** [comment]
TL;DR
Yes, they are the same

Detail
It's because fairseq renamed this arg at commit [72a25a4e52402b6f53aa98cfb739c075c0d6f7ee](https://github.com/pytorch/fairseq/commit/72a25a4e52402b6f53aa98cfb739c075c0d6f7ee#diff-b7473570226affc4c5bcb9a512efb843674f5e84abc86653122442f5c68e038c)

**Comment by Maxwell-Lyu** [comment]
By the way, i've tried to run the train script, the fairseq commit id i'm using is #4cdc81f6f1b16cbb6e1016e3d06a6e4962edcec0.

Latter commit fails with error "AttributeError: 'dict' object has no attribute 'encoder_out'", for your reference.

**Comment by wying8349** [comment]
Thanks.
