### ISSUE TITLE
Inference Error

### ISSUE THREAD

**Issue by zhuyl96** [PANXiao1994/mRASP2#12]
Hey, this is a really great work. But I ran into a problems when using the model for inferences.

You have released three models: `6e6d-no-mono`, `12e12d-no-mono` and `12e12d`.
I try to use `12e12d-no-mono` and `12e12d` to translate Hindi to English. However, this problem is encountered: sometimes `12e12d` cannot decode the token correctly, but `12e12d-no-mono` can decode it correctly. The following is my test sample and the token predicted by the model:

**model: 12e12d**
> S-6	LANG_TOK_HI इस समय आ@@ ठ अं@@ को के साथ इ@@ ट@@ ली पू@@ ल C में ती@@ स@@ रे नं@@ बर पर हैं और इ@@ ट@@ ली को 29 सि@@ तं@@ बर को स@@ ्@@ कॉ@@ ट@@ ल@@ ै@@ ंड के खि@@ ला@@ फ@@ ़ दूस@@ रे मै@@ च में कड@@ ़@@ ी ट@@ क@@ ्@@ कर मि@@ ली ।
H-6	-0.6864292621612549	LANG_TOK_EN Ital@@ y is now on the th@@ ir@@ d spo@@ t in Po@@ ol C with eig@@ ht points and Ital@@ y fo@@ und a tie on September 29 against Sc@@ ot@@ land in a sec@@ ond mat@@ ch .
S-7	LANG_TOK_HI न@@ ्@@ यू@@ ज@@ ़@@ ी@@ ल@@ ै@@ ंड ग@@ ्@@ रु@@ प में प@@ ्@@ रथम श@@ ्@@ रे@@ णी पर , स@@ ्@@ कॉ@@ ट@@ ल@@ ै@@ ंड से 10 प@@ ॉ@@ इं@@ ट से आ@@ गे रहा ।
**H-7	-0.6589236855506897	् न ् यू@@ जी@@ ल@@ ै@@ ंड सम@@ ू@@ ह में पहले श ् रे@@ णी पर , स ् कॉ@@ ट@@ ल@@ ै@@ ंड से 10 प@@ ॉ@@ इं@@ ट से आ@@ गे रहा ।**

**model: 12e12d-no-mono**
> S-6	LANG_TOK_HI इस समय आ@@ ठ अं@@ को के साथ इ@@ ट@@ ली पू@@ ल C में ती@@ स@@ रे नं@@ बर पर हैं और इ@@ ट@@ ली को 29 सि@@ तं@@ बर को स@@ ्@@ कॉ@@ ट@@ ल@@ ै@@ ंड के खि@@ ला@@ फ@@ ़ दूस@@ रे मै@@ च में कड@@ ़@@ ी ट@@ क@@ ्@@ कर मि@@ ली ।
H-6	-0.5951337218284607	LANG_TOK_EN Ital@@ y is cur@@ rent@@ ly th@@ ir@@ d in Po@@ ol C with eig@@ ht points and scor@@ ed a tie against Sc@@ ot@@ land in the sec@@ ond mat@@ ch on September 29 .
S-7	LANG_TOK_HI न@@ ्@@ यू@@ ज@@ ़@@ ी@@ ल@@ ै@@ ंड ग@@ ्@@ रु@@ प में प@@ ्@@ रथम श@@ ्@@ रे@@ णी पर , स@@ ्@@ कॉ@@ ट@@ ल@@ ै@@ ंड से 10 प@@ ॉ@@ इं@@ ट से आ@@ गे रहा ।
H-7	-0.6146384477615356	LANG_TOK_EN In the New Ze@@ al@@ and gro@@ up , it was 10 points a@@ head of Sc@@ ot@@ land in the first clas@@ s .

The following is my script:
**model: 12e12d**
`fairseq-generate ./test_data/bin \
    --user-dir ./mcolt \
    -s hi \
    -t en \
    --path ./model/12e12d_last.pt \
    --max-tokens 1024 \
    --task translation_w_langtok \
    --lang-prefix-tok "LANG_TOK_"`echo "en " | tr '[a-z]' '[A-Z]'` \
    --max-source-positions 1024 \
    --max-target-positions 1024 \
    --nbest 1 | grep -E '[S|H|P|T]-[0-9]+' > ./test_data/trans_res/en_12e12d_last.txt`
**model: 12e12d-no-mono**
`fairseq-generate ./test_data/bin \
    --user-dir ./mcolt \
    -s hi \
    -t en \
    --path ./model/12e12d_no_mono.pt \
    --max-tokens 1024 \
    --task translation_w_langtok \
    --lang-prefix-tok "LANG_TOK_"`echo "en " | tr '[a-z]' '[A-Z]'` \
    --max-source-positions 1024 \
    --max-target-positions 1024 \
    --nbest 1 | grep -E '[S|H|P|T]-[0-9]+' > ./test_data/trans_res/en_12e12d_no_mono.txt`

It can be found that the tokens predicted by the two models for `H-7` are completely inconsistent. The first position should be `LANG_TOK_EN`, but the model is decoded to ` ्`. Of course, the tokens after `LANG_TOK_` are neither fully source language tokens nor target language tokens. In my testset, there are other sentences that have also been decoded into this situation. And their first token is ` ्`.

Why does this happen? Did I not input the parameters expected by `12e12d` correctly?

**Comment by PANXiao1994** [comment]
Hello, your script seems good. And the decoding process should already force the first token to be the language token. Have you met this situation if your change a source language?

**Comment by PANXiao1994** [comment]
Could you add breakpoints in the following lines and try to debug on your own?
* https://github.com/PANXiao1994/mRASP2/blob/master/mcolt/tasks/translation_w_langtok.py#L387
* https://github.com/pytorch/fairseq/blob/main/fairseq/sequence_generator.py#L583 (find the corresponding line in your fairseq version)
