### ISSUE TITLE
请求解答一下Evaluation时的参数意义

### ISSUE THREAD

**Issue by S-GeGe** [PANXiao1994/mRASP2#15]
Evaluation时，执行下面的语句，其参数意义可否详细解答一下：
export NUM_GPU=4 && bash eval.sh ${test_config} ${model_config} ${spm_model} ${bleutype}

@PANXiao1994

**Comment by PANXiao1994** [comment]
test config 是测试文件相关的config文件的路径，model config是模型相关配置文件路径. spm model 是sentence piece model的路径 bleutype是tok或者detok

**Comment by S-GeGe** [comment]
好哒，懂了，多谢解答。

**Comment by Sen-Ran** [comment]
> 好哒，懂了，多谢解答。

打扰一下，请问您成功eval了吗？
