### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by limbo520** [PANXiao1994/mRASP2#16]
请问下论文中指的单向语料是什么意思呢？我个人理解双向语料就是同语义<English,Chinese>的sentence这种形式，但是单向语料没有对应的标签怎么计算交叉熵loss和contrastive loss呢？其次，看代码实现中数据的内容是<String,Coding>的pair对形式，这个和我理解的不太一样，想了好久不知道将pair对的数据处理成这样的。

**Comment by PANXiao1994** [comment]
单向语料会做code switch，然后和原始的句子组成伪平行语料

**Comment by limbo520** [comment]
好的，知道了，万分谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月2日(星期天) 凌晨4:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PANXiao1994/mRASP2] dataset (Issue #16)





 
单向语料会做code switch，然后和原始的句子组成伪平行语料
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
