### ISSUE TITLE
Link broken of datasets

### ISSUE THREAD

**Issue by clarenceguan** [PANXiao1994/mRASP2#18]
Hi, I find some links to the datasets seems to be broken.  And reported the following error "upstream server error". Is there  new links provided? Thanks!

**Comment by PANXiao1994** [comment]
https://github.com/linzehui/mRASP/issues/34

**Comment by clarenceguan** [comment]
> [linzehui/mRASP#34](https://github.com/linzehui/mRASP/issues/34)

I replace the download link prefix with "lf3-nlp-opensource.bytetos.com" but get another error-"object not found".  It looks like this method doesn't work now.

**Comment by PANXiao1994** [comment]
I can open this link : http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/emnlp2020/mrasp/pretrain/dataset/train/32-lang-pairs/download.sh

**Comment by lidh15** [comment]
hi, besides the link, I'd like to know what the total size of each data (mono preprocess, mono binary, etc.) is? so that I can estimate the time and space cost to download them.
