### ISSUE TITLE
Where can I get trained models?

### ISSUE THREAD

**Issue by jaehyoyoo** [PANXiao1994/mRASP2#2]
Hi, i'm very interested in your work and wanna do additional experiments with the model.

Where can I get the trained one?

Thank you for your great job!

**Comment by PANXiao1994** [comment]
Hello. I have just uploaded the trained model.

**Comment by jaehyoyoo** [comment]
Thank you for your effort!

**Comment by surviveMiao** [comment]
> Hello. I have just uploaded the trained model.

Hello, have you reproduced the mrasp2 model? If it is convenient for me to ask you some questions?
