### ISSUE TITLE
The script in new_impl cannot be downloaded

### ISSUE THREAD

**Issue by yinaoxiong** [PANXiao1994/mRASP2#24]
For example, when run follow command will return 403
```
wget -c http://sf3-ttcdn-tos.pstatp.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/download.sh
```

**Comment by surviveMiao** [comment]
> 

Hello, we have encountered some problems in reproducing mRASP2. Would you please leave a contact information as follows?

**Comment by yinaoxiong** [comment]
> For example, when run follow command will return 403
> 
> ```
> wget -c http://sf3-ttcdn-tos.pstatp.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/download.sh
> ```

I found that replacing the domain name sf3-ttcdn-tos.pstatp.com with lf3-nlp-opensource.bytetos.com fixed the problem.

For example

```
wget -c http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/download.sh
```

**Comment by surviveMiao** [comment]
> 



> > For example, when run follow command will return 403
> > ```
> > wget -c http://sf3-ttcdn-tos.pstatp.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/download.sh
> > ```
> 
> I found that replacing the domain name sf3-ttcdn-tos.pstatp.com with lf3-nlp-opensource.bytetos.com fixed the problem.
> 
> For example
> 
> ```
> wget -c http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/download.sh
> ```

Thank you for your answer. It's very helpful to us. Is it convenient to add a contact information for future communication? Qq: 276920603 Please ignore if it is inconvenient. be deeply grateful

**Comment by surviveMiao** [comment]
> lf3-nlp-opensource.bytetos.com
Hello, according to your connection, we downloaded the parallel to_ pub100_ There is only one sentence in all the files in the bin file:{"Success":-1,"error":{"code":4024,"message":"Unauthorized accessEndpoint for bucket access."}} 。Do you know why? Please give us your help if it is convenient. Thank you very much

**Comment by yinaoxiong** [comment]
You also have to replace the domain name in the download.sh file. The domain name in the file download.sh is also wrong.

**Comment by surviveMiao** [comment]
> 



> You also have to replace the domain name in the download.sh file. The domain name in the file download.sh is also wrong.

Sorry to bother you again, thank you for your advice, but after we change the connection in download.sh, we will be prompted 404
![image](https://user-images.githubusercontent.com/96619920/195264793-f2019307-d7fd-45fe-b1e4-c3ebecd00dd2.png)
Do you know how to solve this problem?Thank you for your advice at your convenience，be deeply grateful

**Comment by yinaoxiong** [comment]
> > 
> 
> > You also have to replace the domain name in the download.sh file. The domain name in the file download.sh is also wrong.
> 
> Sorry to bother you again, thank you for your advice, but after we change the connection in download.sh, we will be prompted 404 ![image](https://user-images.githubusercontent.com/96619920/195264793-f2019307-d7fd-45fe-b1e4-c3ebecd00dd2.png) Do you know how to solve this problem?Thank you for your advice at your convenience，be deeply grateful


I directly visit http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/en-ar/train.en-ar.ar.bin it is ok

**Comment by surviveMiao** [comment]
> http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/en-ar/train.en-ar.ar.bin

I'm glad to see your reply. Our team is looking forward to your reply. It has helped us a lot. We have successfully downloaded it according to your connection. Thank you very much

> > > 
> > 
> > 
> > > 您还必须替换 download.sh 文件中的域名。文件 download.sh 中的域名也是错误的。
> > 
> > 
> > 很抱歉再次打扰您，感谢您的建议，但是我们在 download.sh 更改连接后，我们会提示404![图像](https://user-images.githubusercontent.com/96619920/195264793-f2019307-d7fd-45fe-b1e4-c3ebecd00dd2.png)您是否知道如何解决此问题？感谢您在方便时的建议，深表感激
> 
> 我直接访问 http://lf3-nlp-opensource.bytetos.com/obj/nlp-opensource/acl2021/mrasp2/parallel_pub100_bin/en-ar/train.en-ar.ar.bin 还可以

Glad to see your reply. Our team is looking forward to your reply. It has helped us a lot. We have successfully downloaded it according to your connection. Thank you for your help in your busy schedule. Thank you very much
