### ISSUE TITLE
Release of synonym dictionary

### ISSUE THREAD

**Issue by BaohaoLiao** [PANXiao1994/mRASP2#3]
Hi, this is really a great paper. In the paper, you said you would release the synonym dictionary. May I ask when will you release it? In addition, is it a multilingual synonym dictionary? Do you have monolingual synonym dictionary, e.g. only for english.

**Comment by PANXiao1994** [comment]
Hello, I have released the synonym dictionary.

**Comment by BaohaoLiao** [comment]
> Hello, I have released the synonym dictionary.

Thank you very much.
