### ISSUE TITLE
FileNotFoundError: /home/pgye/mRASP2/mlnlc_mt

### ISSUE THREAD

**Issue by YePG** [PANXiao1994/mRASP2#4]
I run the train_w_mono.sh,and raise an error, Can you elaborate on how to use the code, Thank you for a job well done!

**Comment by YePG** [comment]
what is the mlnlc_mt???

**Comment by PANXiao1994** [comment]
Hello. Sorry for the mistake. Actually it's `mcolt`, which is a subdirectory of this repo. I have correct this error.

**Comment by YePG** [comment]
> Hello. Sorry for the mistake. Actually it's `mcolt`, which is a subdirectory of this repo. I have correct this error.

thank u for your job!
