### ISSUE TITLE
pre-norm or post-norm

### ISSUE THREAD

**Issue by jingmu123** [PANXiao1994/mRASP2#7]
您好！我看paper中有提到在训练时你们使用了pre-norm，但我看公布的代码设置仍然是post-norm，请问这个pre-norm的设置是在哪里另外配置了吗

**Comment by PANXiao1994** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/24204710/128681201-c720f93f-88d7-4477-844c-f3ed6c73a0b0.png">

是Pre-norm

**Comment by jingmu123** [comment]
> <img alt="image" width="674" src="https://user-images.githubusercontent.com/24204710/128681201-c720f93f-88d7-4477-844c-f3ed6c73a0b0.png">
> 
> 是Pre-norm


好的，看到了，谢谢您的回复
