### ISSUE TITLE
An error occurred during model inference

### ISSUE THREAD

**Issue by liuwanyue868** [PANXiao1994/mRASP2#8]
I am using the new version. There was an error in the model inference stage. The model used 12e12d_no_mono.pt, the data used the test set binary file provided by you, and other configuration files were reconfigured according to examples/configs/biginfer.
File "XXX/lib/python3.7/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

**Comment by PANXiao1994** [comment]
Hello. This is due to the version of fairseq.
